version: "2.4"

## USG DHCP: [ip],pxelinux.0

## Porteus kiosk: add http ip to `[...]/assets/boot/pxelinux.cfg/default`
## edit lighttp config to allow directory listing

## check for missing `initrdpxe.xz`; downloadable from `https://porteus-kiosk.org/public/`

services:
  asset-host:
    build:
      context: ./asset-host
    image: asset-host
    restart: always
    tty: true
    volumes:
      - assets:/assets
      - lighttpd-config:/etc/lighttpd
    tmpfs:
      - /var/www/localhost
    ports:
      - 8080:80/tcp
  dnsmasq:
    build:
      context: ./dnsmasq
    image: dnsmasq
    restart: always
    command: --dhcp-boot=pxelinux.0,172.16.0.66,172.16.0.66 --dhcp-range=172.160.0.66,proxy
    volumes:
      - assets:/var/lib/tftpboot
    cap_add:
      - NET_ADMIN
    ports:
      - 69:69/udp

volumes:
  assets:
  lighttpd-config:
