version: "2.4"

services:
  asset-host:
    build:
      context: ./asset-host
    image: asset-host
    restart: always
    tty: true
    volumes:
      - netboot-asset:/assets
      - lighttpd-config:/etc/lighttpd
    tmpfs:
      - /var/www/localhost
    ports:
      - 8080:80/tcp
  netbootxyz:
    image: linuxserver/netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - netboot-config:/config
      - netboot-asset:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
    restart: unless-stopped

volumes:
  lighttpd-config:
  netboot-asset:
  netboot-config:
