version: "2.4"

services:
  asset-host:
    build:
      context: ./asset-host
    image: asset-host
    restart: always
    tty: true
    volumes:
      - asset-storage:/assets
      - asset-config:/etc/lighttpd
    tmpfs:
      - /var/www/localhost
    ports:
      - 8080:80/tcp
  pxe-server:
    image: taskinen/tftp
    restart: always
    volumes:
      - tftp:/var/tftpboot:ro
    ports:
      - 69:69/udp

volumes:
  asset-storage:
  asset-config:
  tftp:
